### ISSUE TITLE
command buffer is focused every time for some single-key commands

### ISSUE THREAD

**Issue by LukeXuan** [realgud/realgud#189] opened 2017-09-26 08:00 UTC
Hi, I'm using gdb(built from homerbew) on Mac OS 10.12, when I step/next, the result from gcc seems producing two ^Z at the beginning of line. Causing the cmdbuf is focused everytime. Is there any solution for this problem?

**Comment by LukeXuan** [comment] 2017-09-26 08:00
![image](https://user-images.githubusercontent.com/3363954/30849096-36f0b046-a26f-11e7-9056-828c89aa691e.png)
It's like this

**Comment by rocky** [comment] 2017-09-26 08:30
> Causing the cmdbuf is focused everytime

I don't understand what this means.  

Here what is going on - the control-z's are added by gdb's annotation mode and signal the beginning of something that realgud should pay attention to. I'd like to understand exactly what problem the above is causing. Is this just an aesthetic thing?

It might be possible to add a hook function onto gdb to remove that. I think something like this might be done to strip escape characters from nodejs. See 
https://github.com/realgud/realgud/blob/master/realgud/debugger/nodejs/track-mode.el#L39-L47 

Perhaps you could experiment with that.

**Comment by LukeXuan** [comment] 2017-09-26 08:35
Well, it's only my guess, which seems to be ridiculous.

The real problem I'm experiencing is, every time I use `realgud:cmd-next` in `srcbuf`, the `cmdbuf` is focused. Even if I invoked `realgud-cmdbuf-stay-in-source-toggle`.

I only found the problem in past issues suggesting that it's debugger-side problem, thus I made the previous guess.

**Comment by LukeXuan** [comment] 2017-09-26 08:35
I would like to filter the escape characters out, but it does not matter so much.

**Comment by rocky** [comment] 2017-09-26 08:38
I have often observed that when one solicits the reporter to try to address issues they encounter, all of a sudden the issue is no longer important ;-)

**Comment by LukeXuan** [comment] 2017-09-26 08:40
Well.. I would love to fix the aesthetic thing. But as I stated before, the aesthetic thing is a minor problem for me...

**Comment by LukeXuan** [comment] 2017-09-26 08:42
I'm composing the original title because it was the reason I guess, causing the focus of two buffers to behave strangely, but not stating that it's the problem I want to fix, please understand.

**Comment by rocky** [comment] 2017-09-26 12:24
Ok. This this is a duplicate of #169 then.

**Closed by rocky** 2017-09-26 12:24 UTC
Labels: duplicate
