### ISSUE TITLE
Feature request for python: please support many windows and frame.

### ISSUE THREAD

**Issue by 9527KGG** [realgud/realgud#235] opened 2019-02-14 05:14 UTC
Comparing to Emacs default gud **gdb**,  2 features are missing for python debug:

1. Many windows. Other debugger, such as VS code python debugger can support many windows.
Two similar requests for gdb, (not python, which I am suggesting)
https://github.com/realgud/realgud/issues/219
https://github.com/realgud/realgud/issues/99  
2. Frame.  In Emacs default gud gdb, it is: menu -> Gud -> GDB Frame. This is a very useful feature when you have 2+ monitors. You can view stuffs in different Windows, side by side, in 2+ monitors. Eg

![image](https://user-images.githubusercontent.com/12282281/52764565-91abb680-2fd5-11e9-9721-eb2dd170b70e.png)

**_Frame is a clear win for Emacs over Vim/Vscode, since they are never ever able to support frame, which are across multiple monitors._**

**Comment by rocky** [comment] 2020-03-17 11:16
Window support is independent of the debugger. Duplicate of #236 .

**Closed by rocky** 2020-03-17 11:16 UTC
